/* ---------- Toolkit: capability types (no brands) ---------- */
const CAPS = {
  extract:  {name:'Document extraction', one:'Reads documents, emails and forms and pulls out the specific fields you need.',
    good:['Invoices, purchase orders, contracts, claims','Mixed layouts from many senders','Turning free-text requests into structured fields'],
    needs:'Samples of the real documents, and somewhere for the fields to land once extracted.',
    watch:'Confidence varies by field. Route low-confidence items to a person instead of trusting everything.'},
  summarize:{name:'Summarization', one:'Condenses long material into what matters: threads, calls, case histories, reports.',
    good:['Case handover notes','Meeting and call recaps','Digesting many supplier emails at once'],
    needs:'Access to the source material and a clear view of what matters to the reader.',
    watch:'It can flatten nuance. Specify what must never be dropped: dates, amounts, commitments.'},
  retrieve: {name:'Knowledge retrieval & Q&A', one:'Finds the relevant passage in policies, manuals or system records and answers in plain language.',
    good:['Answering questions from a document library','Grounded answers that cite their source','Internal help for staff'],
    needs:'A trustworthy, current set of documents or data to point at.',
    watch:'Stale or contradictory documents produce confident wrong answers. Curate the source first.'},
  vision:   {name:'Computer vision', one:'Interprets images and video: reads labels, counts items, spots defects or damage.',
    good:['Inspection and quality checks','Reading labels, meters, plates','Counting stock or verifying a packed order'],
    needs:'Consistent images and labelled examples of what to detect.',
    watch:'Lighting, angle and camera quality make or break it. Pilot in the real environment.'},
  speech:   {name:'Speech & voice', one:'Turns speech into text and back: transcribes calls, captures notes, powers voice interfaces.',
    good:['Call transcription and after-call notes','Hands-free capture in the field','Voice-based ordering or lookup'],
    needs:'Decent audio and consent to record.',
    watch:'Accents, jargon and background noise reduce accuracy. Pair with a review step for anything binding.'},
  classify: {name:'Classification & routing', one:'Sorts items into categories: intents, priorities, teams, risk levels.',
    good:['Triaging inboxes and tickets','Tagging cases by type or urgency','Sending work to the right queue'],
    needs:'Clear categories and examples of items in each.',
    watch:'Ambiguous items need an "unsure" bucket. Measure misroutes, not just speed.'},
  anomaly:  {name:'Anomaly & error detection', one:'Flags items that do not look like the rest: duplicates, unusual amounts, suspicious changes.',
    good:['Duplicate or fraudulent payments','Data-entry errors','Unusual demand spikes'],
    needs:'A baseline of normal, and a person to investigate what gets flagged.',
    watch:'Tune the threshold. Too many flags and people stop looking.'},
  predict:  {name:'Prediction & forecasting', one:'Estimates a number or likelihood from historical patterns: demand, churn, lead time, risk.',
    good:['Demand and volume forecasts','Likelihood scores (churn, late payment)','Estimating durations and costs'],
    needs:'Enough history at the right granularity, including the outcomes you want to predict.',
    watch:'Patterns shift. Monitor accuracy and let planners override with a reason.'},
  recommend:{name:'Recommendation & decision support', one:'Ranks options and surfaces the evidence so a person decides faster and more consistently.',
    good:['Suggesting substitutes or next steps','Prioritising a work queue','Showing the policy, history and precedent for a judgment call'],
    needs:'Outcome data or clear criteria for what good looks like.',
    watch:'Keep the person accountable for the decision. Log why suggestions were overridden.'},
  optimize: {name:'Optimization & scheduling', one:'Finds the best plan under constraints: routes, schedules, stock allocation, staffing.',
    good:['Delivery routing','Order quantities across warehouses','Shift and job scheduling'],
    needs:'Explicit constraints and a clear objective: cost, time or service level.',
    watch:'Real life has unstated constraints. Let planners edit the plan and feed the reasons back.'},
  draft:    {name:'Drafting & generation', one:'Writes a first version: emails, descriptions, reports, documents from a template.',
    good:['Replies that follow a pattern','Product descriptions, job posts, briefs','Turning bullet notes into prose'],
    needs:'Examples of good output and the facts to include.',
    watch:'Drafts, not decisions. Someone accountable reviews anything sent outside.'},
  converse: {name:'Conversational assistant', one:'A natural-language front door for customers or staff, answering and acting within set limits.',
    good:['Self-service for common questions','Guided intake ("what do you need?")','Internal assistants over policy and systems'],
    needs:'A well-defined scope, connected data, and a graceful handoff to a person.',
    watch:'Only as good as what it is connected to. A chatbot over bad documentation is a faster way to be wrong.'},
  agent:    {name:'Agentic workflow automation', one:'Carries out multi-step tasks across systems: looks things up, fills forms, sends messages, escalates.',
    good:['Chasing and coordinating routine follow-ups','Multi-system tasks with variable inputs','Preparing a case so a person only approves'],
    needs:'System access, clear stopping rules, and a log of every action taken.',
    watch:'Errors compound across steps. Start with "propose, then a person approves" before letting it act alone.'},
  rules:    {name:'Rules-based automation (no AI)', one:'If the logic can be written down as rules, a workflow tool or your existing system does it reliably and cheaply.',
    good:['Three-way matching','Generating standard documents','Threshold approvals and reminders'],
    needs:'Stable rules and structured data.',
    watch:'Do not reach for AI when a rule will do. Do not force rules on work that is truly variable.'},
  fix:      {name:'Fix the process (no tool)', one:'Sometimes the step only exists because of a broken handoff, a missing field or a bad form. Remove the cause.',
    good:['Removing rework loops','Capturing data at the source','Self-service instead of handling requests'],
    needs:'Permission to change the process, and the upstream owner in the room.',
    watch:'Automating a broken process makes it break faster.'},
};

const CAP_FAMILIES = [
  {id:'read',  name:'Read & understand',      caps:['extract','summarize','retrieve','vision','speech']},
  {id:'judge', name:'Sort, predict & decide',  caps:['classify','anomaly','predict','recommend','optimize']},
  {id:'act',   name:'Create & act',            caps:['draft','converse','agent']},
  {id:'none',  name:'Not an AI problem',       caps:['rules','fix']},
];

/* ---------- Anatomy of a task: the four dimensions ---------- */
const SHAPES = [
  {id:'extract',   name:'Read & pull out facts',      d:'Take documents or messages and get the specific details out of them.'},
  {id:'route',     name:'Sort, tag & route',          d:'Decide which bucket, queue or person each item goes to.'},
  {id:'lookup',    name:'Look up & answer',           d:'Find information that already exists and respond to a question.'},
  {id:'draft',     name:'Write & draft',              d:'Produce text: replies, descriptions, documents.'},
  {id:'summarize', name:'Condense & summarize',       d:'Turn a lot of material into the few things that matter.'},
  {id:'predict',   name:'Estimate & forecast',        d:'Put a number or likelihood on something that has not happened yet.'},
  {id:'check',     name:'Check & flag',               d:'Compare against what is expected and flag what is off.'},
  {id:'suggest',   name:'Suggest & rank options',     d:'Propose the best next step, item or action from many possibilities.'},
  {id:'allocate',  name:'Allocate & schedule',        d:'Fit many things into limited capacity under constraints.'},
  {id:'decide',    name:'Judge & decide',             d:'Weigh a situation and make a call someone is accountable for.'},
  {id:'coordinate',name:'Chase, coordinate & update', d:'Follow up with people and move information between systems.'},
  {id:'physical',  name:'Handle or inspect physically',d:'Move, pack, count or examine real things.'},
];
const INPUTS = [
  {id:'structured', name:'Structured data',       d:'Fields, tables, system records.'},
  {id:'text',       name:'Unstructured text',     d:'Emails, PDFs, notes, chat.'},
  {id:'media',      name:'Images, audio or video', d:'Photos, scans that are really pictures, recordings, calls.'},
  {id:'tacit',      name:'Not captured anywhere', d:'In people\u2019s heads, on calls nobody records.'},
];
const REPS = [
  {id:'high', name:'High',   d:'Many times a day, similar each time.'},
  {id:'mid',  name:'Medium', d:'Regular, but each one varies.'},
  {id:'low',  name:'Low',    d:'Rare or one-off.'},
];
const STAKES = [
  {id:'low',  name:'Low',    d:'Clear rules; an error is cheap to fix.'},
  {id:'mid',  name:'Medium', d:'Some judgment; errors cost time or money.'},
  {id:'high', name:'High',   d:'Nuanced judgment; regulated or costly errors.'},
];
const AUTONOMY = [
  {id:'assist', name:'Assist',               d:'AI prepares; a person decides every case.'},
  {id:'review', name:'Automate with review', d:'AI handles the routine; people see the exceptions.'},
  {id:'auto',   name:'Fully automate',       d:'AI acts; people watch the metrics.'},
];
const LEVELS = [
  {id:'low', name:'Low'},{id:'mid', name:'Medium'},{id:'high', name:'High'},
];
const DIMS = [
  {id:'shape',  label:'Shape of the work',      q:'What is the person actually doing?',                 opts:SHAPES},
  {id:'input',  label:'Inputs',                 q:'What does the work start from?',                     opts:INPUTS},
  {id:'rep',    label:'Volume & repetition',    q:'How often, and how similar each time?',              opts:REPS},
  {id:'stakes', label:'Judgment & stakes',      q:'How much judgment, and what does an error cost?',    opts:STAKES},
];

const GUARDRAILS = [
  {id:'threshold', name:'Confidence threshold',     d:'Low-confidence items go to a person.'},
  {id:'logging',   name:'Log every action',         d:'Each decision or action is recorded and reviewable.'},
  {id:'privacy',   name:'Personal data per policy', d:'Minimum data, right storage, access controls.'},
  {id:'escalation',name:'Clear path to a person',   d:'Anyone can hand off or appeal to a human quickly.'},
  {id:'rollback',  name:'Rollback plan',            d:'The manual process can resume within a day.'},
  {id:'sampling',  name:'Accuracy sampling',        d:'Regularly check outputs against ground truth.'},
  {id:'bias',      name:'Fairness review',          d:'Check outcomes across groups when people are affected.'},
];

/* ---------- The fictional company ---------- */
const COMPANY = {
  name:'Brightwater Supply Co.',
  blurb:'A regional distributor of facility and janitorial supplies: 640 people, three warehouses, 4,000 business customers, $420M in revenue. Profitable, busy, and running on spreadsheets, email and a fifteen-year-old ERP.',
  role:'You have just been asked to lead the search for where AI could help. Leadership wants ideas by the end of the quarter. Nobody has asked which processes need help first. That is your job.',
};

const FUNCTIONS = [
  {id:'sales', name:'Sales & accounts', chain:true,
   brief:'42 reps and account managers look after 4,000 business customers and produce about 260 quotes a week.',
   signals:[{t:'Quotes take two days to turn around; two competitors quote same-day.', s:'strong'},{t:'Reps spend Friday afternoons updating the CRM from memory.', s:'medium'}],
   processes:[
    {id:'quotes', name:'Quote & proposal preparation', d:'Assemble prices, terms and product details into a proposal.', rating:4, why:'High volume and repetitive assembly from price lists and templates, with a measured pain (two-day turnaround). Variable enough to need judgment on terms, so a strong assist candidate.'},
    {id:'crm', name:'CRM updates & call logging', d:'Record what happened in customer calls and meetings.', rating:3, why:'Real, daily and disliked. Transcription and summarization can capture notes. The value is indirect (better data) rather than a direct cost.'},
    {id:'acctplan', name:'Annual account planning', d:'Set strategy and targets for each key account.', rating:1, why:'Once a year, high judgment, few items. Painful, but pain without volume is not a hotspot.'},
   ]},
  {id:'orderdesk', name:'Order desk', chain:true,
   brief:'38 customer-service reps handle around 2,300 emails and 900 calls every day, keying orders into the ERP and answering questions.',
   signals:[{t:'The average email takes 11 minutes to handle; three people do nothing but sort the shared inbox.', s:'strong'},{t:'2.4% of orders are keyed with an error and ship wrong.', s:'strong'}],
   processes:[
    {id:'orders', name:'Inbound orders & inquiries', d:'Receive orders, questions and complaints by email and phone; enter, answer, confirm.', rating:5, authored:'A', why:'Very high volume, highly repetitive, measured pain on cost and on quality, and the inputs (emails, PDFs, calls) are already captured. The textbook hotspot.'},
    {id:'newacct', name:'New customer account setup', d:'Create the account, run a credit check, set up pricing.', rating:2, why:'Only 30 a week, and mostly a form plus a credit-bureau check. Fix the form and automate the rules; AI adds little.'},
   ]},
  {id:'procure', name:'Procurement & inventory', chain:true,
   brief:'Six buyers manage 18,000 active products across three warehouses and 900 suppliers, on a weekly buying cycle run from spreadsheets.',
   signals:[{t:'6% of order lines stock out; meanwhile $14M of inventory is excess.', s:'strong'},{t:'Buyers spend around 60% of their week in spreadsheets.', s:'strong'}],
   processes:[
    {id:'replen', name:'Replenishment planning', d:'Forecast demand, watch supplier signals, decide what to order where, raise POs.', rating:5, authored:'C', why:'Thousands of decisions a week, rich history in the ERP, and a very large measured cost on both sides (stockouts and excess). Prediction and optimization territory.'},
    {id:'contracts', name:'Supplier contract negotiation', d:'Negotiate terms and pricing with key suppliers.', rating:2, why:'A few dozen a year and heavily judgment-based. AI can summarize contracts as a helper, but this is not where the volume is.'},
   ]},
  {id:'warehouse', name:'Warehouse & delivery', chain:true,
   brief:'Three warehouses, 310 staff and 41 trucks pick, pack and deliver around 1,100 orders a day.',
   signals:[{t:'Routes are planned by hand every morning. It takes 90 minutes and trucks still come back half empty.', s:'medium'},{t:'Picking errors run at 0.8%.', s:'weak'}],
   processes:[
    {id:'pick', name:'Picking & packing', d:'Walk the aisles, pick items, pack and label them.', rating:2, why:'Physical work. Software AI helps at the edges (vision checks at packing, better slotting); automating the handling itself is a robotics investment, a different decision.'},
    {id:'routes', name:'Delivery route planning', d:'Assign the day\u2019s deliveries to trucks and sequence the stops.', rating:4, why:'Daily, constrained, measurable, and the data (addresses, windows, truck capacity) exists. Classic optimization; strong even without generative AI.'},
    {id:'receive', name:'Inbound receiving & put-away', d:'Check deliveries against POs and put stock away.', rating:3, why:'Regular and measurable. The main lever is recording receipts promptly (a process fix), with scanning or vision to speed the checks.'},
   ]},
  {id:'finance', name:'Finance', chain:true,
   brief:'34 people run payables, receivables, payroll and reporting; the team processes about 9,000 supplier invoices a month.',
   signals:[{t:'Processing an invoice costs $9.40; the best-run teams do it for under $3.', s:'strong'},{t:'Month-end close takes nine working days.', s:'medium'}],
   processes:[
    {id:'ap', name:'Invoice to payment (AP)', d:'Receive supplier invoices, match to orders and receipts, resolve exceptions, approve, pay.', rating:5, authored:'B', why:'High volume, documents already digital, a benchmarked cost gap of over $6 per invoice, and clear rules for most of it. Extraction, anomaly detection and plain rules.'},
    {id:'ar', name:'Collections & cash application', d:'Chase overdue customers and match incoming payments to invoices.', rating:4, why:'Repetitive chasing, remittance documents to read, and late-payment risk to predict. A strong second candidate in finance.'},
    {id:'close', name:'Month-end close', d:'Reconcile accounts and produce the monthly numbers.', rating:3, why:'Painful but monthly, and much of it is reconciliation logic that rules and anomaly detection handle. Worth a look after the higher-volume processes.'},
   ]},
  {id:'people', name:'People (HR)', chain:false,
   brief:'Nine people support 640 employees and around 120 hires a year.',
   signals:[{t:'Managers ask HR the same policy questions again and again: 900 tickets a quarter.', s:'medium'},{t:'Time to hire is 52 days.', s:'medium'}],
   processes:[
    {id:'policyq', name:'Employee policy questions', d:'Answer questions about leave, expenses, benefits and policy.', rating:4, why:'Repetitive, low stakes, and the answers are in documents that already exist. Retrieval and Q&A over the policy library is a natural fit.'},
    {id:'recruit', name:'Recruiting & screening', d:'Source, screen, interview and select candidates.', rating:2, why:'Decisions about people are high stakes and regulated in many places, and the volume is modest. Possible in assist mode later; not a first expedition.'},
    {id:'onboard', name:'Onboarding', d:'Set up accounts, equipment, training and paperwork for new hires.', rating:3, why:'Mostly a coordination checklist across systems: rules-based workflow first, with an agent for the chasing.'},
   ]},
  {id:'it', name:'IT', chain:false,
   brief:'22 people support the systems and around 1,400 helpdesk tickets a month.',
   signals:[{t:'40% of tickets are password resets and access requests.', s:'strong'}],
   processes:[
    {id:'helpdesk', name:'Helpdesk ticket handling', d:'Triage, resolve or escalate IT requests.', rating:4, why:'High volume and repetitive. The biggest slice (resets and access) is a rules and self-service fix; classification and retrieval handle the rest.'},
    {id:'roadmap', name:'Technology roadmap', d:'Decide the next three years of systems investment.', rating:1, why:'Annual, strategic and judgment-heavy. Not a process to automate.'},
   ]},
  {id:'marketing', name:'Marketing', chain:false,
   brief:'Eight people run campaigns, the catalogue and the website.',
   signals:[{t:'Content production is the bottleneck for every campaign.', s:'medium'}],
   processes:[
    {id:'content', name:'Campaign content production', d:'Write and produce emails, product copy and web pages.', rating:3, why:'Drafting fits and volume is steady, but brand review keeps a person in every loop and the value is harder to measure than cost per invoice.'},
    {id:'tradeshow', name:'Trade show planning', d:'Plan and run the four annual trade shows.', rating:1, why:'Four times a year. A checklist problem.'},
   ]},
];

/* ---------- Three processes with full field access ---------- */
const PROCESSES = {
 A:{ id:'A', name:'Inbound orders & inquiries', fn:'Order desk',
  intro:'Every order, question and complaint from 4,000 customers arrives at the order desk by email or phone. Thirty-eight reps read, sort, key in, look up and reply. Walk the process one step at a time.',
  steps:[
   {id:'A1', name:'Triage the shared inbox', who:'3 inbox sorters', volume:'2,300 emails a day', systems:'Shared mailbox',
    notes:'Everything lands in one mailbox. Three people read each message just far enough to decide what it is: a new order, a change to an order, a delivery question, a pricing question, a complaint, or noise. They drag it to the right folder for the rep teams. Most messages are obvious in a second; a few need a second read.',
    pain:'Three full-time people sorting; urgent items wait in the pile with everything else.',
    expert:{shape:'route', shapeAlt:[], input:'text', inputAlt:[], rep:'high', repAlt:[], stakes:'low', stakesAlt:['mid']},
    profileNotes:{shape:'The work is deciding which bucket each message belongs in. That is sorting and routing, whatever else the sorters notice along the way.', input:'The inputs are emails: unstructured text with attachments.', rep:'Over two thousand a day, and most look alike.', stakes:'A misrouted email costs a few minutes when a rep forwards it on. Low, with a caveat for the urgent ones.'},
    fit:{best:['classify'], ok:['agent','rules']},
    fitNotes:{classify:'Sorting messages into a fixed set of categories is classification. It handles the messy phrasing that keyword rules miss.', agent:'Workable: an agent can classify and then move the message and notify the team, but the core task is classification. Start there.', rules:'Workable as a first pass. Keyword rules already exist here and catch about 40%. They will not handle "the usual plus 6 cases" or a complaint hidden inside an order.', converse:'Nobody is having a conversation at this step. The messages need sorting, not answering.', draft:'Nothing is being written here.', extract:'Close, but pulling out the fields is the next step. This step only needs to know what kind of message it is.'},
    poorNote:'This capability answers a different question from the one this step asks. Look at the shape of the work again: it is sorting.',
    expertPick:'classify', expertWhy:'Classification with a confidence threshold: confident messages route automatically, unsure ones go to a person. The three sorters become the exception handlers and the people who define new categories.',
    autoBest:'auto', autoOk:['review'], autoNote:'Low stakes and easy to reverse: full automation with an "unsure" bucket fits. Review mode works but keeps a person reading every message, which is the cost you are trying to remove.',
    discoveries:[{title:'The sorters are the glue', text:'The three sorters also spot VIP customers and urgent orders by eye. Nobody has written down how they do it.', effect:'Change effort: capture their rules as categories and keep them on exceptions. Adoption depends on it.'},{title:'The mailbox can act', text:'IT confirms the email system can apply labels and move messages automatically once given a category.', effect:'Integration: low effort.'}],
    expertFeas:'high', expertValue:'high', realityNote:'Data is already digital, integration is simple and three people spend all their time on it. A quick win, provided the sorters help define the categories.',
    metric:'Minutes from arrival to the right queue, and misroute rate', guardrails:['threshold','sampling','escalation'],
    valueHyp:'Free most of three full-time sorters for exception handling and cut time-to-queue from hours to minutes.',
    dataNeeded:'A few thousand past emails labelled with the six categories; the mailbox API for moving messages.'},
   {id:'A2', name:'Capture order details', who:'Order-entry reps', volume:'1,100 orders a day', systems:'ERP, product catalogue',
    notes:'Sixty percent of orders arrive as PDF purchase orders in the customer\u2019s own layout; the rest are free-text emails like "the usual plus six cases of the blue towels." A rep reads the order, finds the customer account, works out which product each line means, and keys quantities, ship-to and requested date into the ERP.',
    pain:'Nine minutes per order on average; 2.4% of orders keyed with an error that ships wrong.',
    expert:{shape:'extract', shapeAlt:[], input:'text', inputAlt:[], rep:'high', repAlt:[], stakes:'mid', stakesAlt:['high']},
    profileNotes:{shape:'The rep is pulling specific facts out of a document or message: customer, lines, quantities, dates. That is extraction, even when the last motion is typing.', input:'PDFs in hundreds of layouts and free-text emails: unstructured text.', rep:'Over a thousand a day, similar in kind if not in format.', stakes:'A wrong product ships and comes back: medium stakes, real money, mostly caught later.'},
    fit:{best:['extract'], ok:['agent','rules','speech']},
    fitNotes:{extract:'Reading many layouts and free text and producing structured fields is exactly document extraction. The hard part, matching "blue towels" to a product, is part of the same capability with a good catalogue behind it.', agent:'Workable: an agent can extract and then create the ERP order. Prove the extraction first, then let it act.', rules:'Template-based OCR is a rules approach. It works for the top 20 customer layouts and breaks on the other 380 and on free text.', speech:'Only relevant for the phone orders. The emails and PDFs are text.', classify:'Knowing the type of message was the previous step. Here you need the contents.', converse:'Customers are not chatting. They have already sent the order.'},
    poorNote:'This step needs the contents of a document turned into fields. Pick the capability that reads.',
    expertPick:'extract', expertWhy:'Document extraction that produces a draft order for the rep to confirm. Each field carries a confidence score, so confident orders from known customers can go straight to the ERP over time.',
    autoBest:'review', autoOk:['auto'], autoNote:'Medium stakes: start with a rep confirming each extracted order, then let confident orders flow through. Assist mode alone would leave the rep doing all the typing.',
    discoveries:[{title:'Four hundred layouts, and free text', text:'Customers use 400 different PO templates; 40% of orders are free-text emails; 12% already arrive by EDI and need nothing.', effect:'Data variety: modern extraction handles it, template OCR would not. Scope the EDI orders out.'},{title:'Nine kinds of blue towel', text:'The product catalogue has about 3,000 duplicate or ambiguous product names. "Blue towels" matches nine items.', effect:'Data readiness: the catalogue needs cleaning before matching can be trusted.'}],
    expertFeas:'mid', expertValue:'high', realityNote:'The biggest prize on the desk, held back by the catalogue. Feasible, but the catalogue clean-up sits on the critical path, so it lands as a strategic bet rather than a quick win.',
    metric:'Minutes per order entered, and order-entry error rate', guardrails:['threshold','sampling','rollback'],
    valueHyp:'Cut order entry from nine minutes to under two of review, and halve the 2.4% error rate.',
    dataNeeded:'Sample POs and emails with the correct ERP order alongside; a cleaned product catalogue with aliases.'},
   {id:'A3', name:'Answer status and pricing questions', who:'Rep teams', volume:'700 questions a day', systems:'ERP, carrier tracking, contract pricing',
    notes:'"Where is my order?" and "what is my price on this?" make up a third of the mail. The rep opens the ERP for order status, the carrier site for tracking, and the contract system for the customer\u2019s price, then writes a short reply.',
    pain:'Three systems and four minutes for a question whose answer already exists somewhere.',
    expert:{shape:'lookup', shapeAlt:['draft'], input:'structured', inputAlt:['text'], rep:'high', repAlt:[], stakes:'low', stakesAlt:[]},
    profileNotes:{shape:'The work is finding an answer that already exists and passing it on: look up and answer. Writing the reply is the easy part.', input:'The question arrives as text, but the answers live in structured system records, and that is what the tool must reach.', rep:'Seven hundred a day, nearly identical.', stakes:'A wrong tracking number is annoying, not costly. Low.'},
    fit:{best:['retrieve','converse','fix'], ok:['agent','draft','rules']},
    fitNotes:{retrieve:'Retrieval over the three systems, with a plain-language reply generated from what it finds, answers the question at the source.', converse:'A conversational front door for customers would let them ask directly and get the answer from the same data.', fix:'Sixty percent of these questions are answered by a portal the company already has. Getting customers to use it may beat any new tool.', agent:'Workable: an agent can look up across the three systems and draft the reply. Retrieval is the core; the agent adds the legwork.', draft:'Workable only with the facts pulled in first. A fluent reply with the wrong status is worse than a slow one.', rules:'Workable: status notifications can be rules-based (send tracking when it ships) and remove many questions before they are asked.'},
    poorNote:'This step needs information found and returned. Pick a capability that finds answers.',
    expertPick:'retrieve', expertWhy:'Two moves together: proactive notifications and a working self-service portal remove most questions; retrieval over the three systems drafts answers to the rest for a rep to send.',
    autoBest:'review', autoOk:['auto'], autoNote:'Low stakes, but replies go to customers: start with reps sending the drafted answer, then move status questions to fully automatic once accuracy is proven.',
    discoveries:[{title:'Three systems, no shared key', text:'Carrier tracking, ERP status and contract pricing sit in three systems with no shared customer identifier.', effect:'Integration: medium effort to join the data.'},{title:'The portal nobody uses', text:'Sales confirms about 60% of these questions could be answered by the customer portal that already exists. Almost no customers use it.', effect:'A process and adoption fix competes with any new tool here.'}],
    expertFeas:'mid', expertValue:'mid', realityNote:'Worth doing, but the first move is not AI: fix portal adoption and send proactive updates, then let retrieval handle what remains.',
    metric:'Questions per hundred orders, and minutes per question answered', guardrails:['sampling','escalation','rollback'],
    valueHyp:'Halve the volume of status questions and cut handling time for the rest from four minutes to under one.',
    dataNeeded:'Read access to ERP, carrier and contract systems with a common customer key; portal usage data.'},
   {id:'A4', name:'Handle complaints and returns', who:'Senior reps', volume:'90 cases a day', systems:'ERP, contract PDFs, warehouse',
    notes:'A customer says the delivery was short, damaged or wrong. The rep reads the thread, checks what shipped, finds the customer\u2019s return terms (often negotiated and buried in a contract PDF), decides whether to credit, and arranges the pickup with the warehouse.',
    pain:'Forty minutes per case; inconsistent decisions between reps; revenue leaks when credits are given too easily.',
    expert:{shape:'decide', shapeAlt:['lookup'], input:'text', inputAlt:['structured'], rep:'mid', repAlt:['high'], stakes:'high', stakesAlt:['mid']},
    profileNotes:{shape:'At its core someone is making a judgment call they are accountable for: is this credit warranted? Everything else is preparation for that decision.', input:'Email threads and contract PDFs: unstructured text, with some structured shipment data.', rep:'Ninety a day is regular, but every case is different.', stakes:'Customer relationships and real money, with negotiated terms to honour: high.'},
    fit:{best:['summarize','retrieve','recommend'], ok:['draft','classify']},
    fitNotes:{summarize:'The slow part is reading. A case summary (what was ordered, shipped, claimed and promised) gets the rep to the decision faster.', retrieve:'Surfacing the customer\u2019s actual return terms from the contract removes the guessing that causes inconsistent decisions.', recommend:'Decision support: propose a disposition with the evidence, and let the rep decide. Consistency improves without removing accountability.', draft:'Workable for the reply once the decision is made. It does not help make it.', classify:'Workable as triage by severity or type, so the right rep gets the case.', agent:'Automating the decision and the credit end to end is the wrong place to start: high stakes, variable cases, and a person needs to own the call.', rules:'The return policy has dozens of negotiated exceptions. Rules would be wrong for many customers.'},
    poorNote:'This is a judgment call with money and relationships attached. AI earns its place by preparing the decision, not making it.',
    expertPick:'recommend', expertWhy:'Assist mode: summarize the case, retrieve the customer\u2019s terms and past claims, and suggest a disposition with reasons. The rep decides and the decision is logged.',
    autoBest:'assist', autoOk:['review'], autoNote:'High stakes and every case different: a person decides every case. Full automation would trade forty minutes of rep time for unrecoverable customer and revenue risk.',
    discoveries:[{title:'Forty flavours of policy', text:'Return terms have about 40 customer-specific exceptions, each documented in a contract PDF.', effect:'Retrieval over contracts is valuable; judgment stays with the rep.'},{title:'Personal data in the thread', text:'Legal notes that complaint threads contain personal data. Any tool must comply with the data-handling policy.', effect:'Risk: a compliance review is on the path.'}],
    expertFeas:'mid', expertValue:'mid', realityNote:'A solid assist use case with a compliance step on the way. Medium on both axes: build toward it after the quick wins.',
    metric:'Minutes per case, and consistency of credit decisions on audit', guardrails:['privacy','logging','escalation'],
    valueHyp:'Cut case handling from forty minutes to fifteen and reduce unwarranted credits by a quarter.',
    dataNeeded:'Case threads, shipment records and contract terms indexed by customer; past decisions and their outcomes.'},
   {id:'A5', name:'Propose substitutes for out-of-stock lines', who:'Order-entry reps', volume:'180 lines a day', systems:'ERP inventory, product catalogue',
    notes:'About one order in six has a line the warehouse cannot fill. The rep looks for something equivalent (same size, same grade, a different brand), checks it is in stock and priced, and asks the customer or applies a substitute the customer has accepted before.',
    pain:'Depends on individual reps knowing the catalogue; new reps guess; backorders that could have been filled.',
    expert:{shape:'suggest', shapeAlt:['lookup'], input:'structured', inputAlt:['tacit'], rep:'high', repAlt:['mid'], stakes:'mid', stakesAlt:[]},
    profileNotes:{shape:'The rep is choosing the best option from many: suggest and rank.', input:'Inventory and catalogue are structured. The knowledge of what substitutes for what is mostly in experienced reps\u2019 heads.', rep:'Nearly two hundred a day.', stakes:'A poor substitute comes back: medium.'},
    fit:{best:['recommend'], ok:['rules','draft','agent']},
    fitNotes:{recommend:'Ranking candidate substitutes from attributes, stock and what this customer accepted before is recommendation.', rules:'Workable: a curated substitute table covers the common cases. It will not learn from what customers actually accept.', draft:'Workable for writing the offer to the customer once a substitute is chosen.', agent:'Workable later: an agent could propose, offer and apply pre-approved substitutes end to end.', predict:'You are not forecasting a quantity. You are choosing an item.'},
    poorNote:'This step is about choosing well among options. Pick the capability that ranks.',
    expertPick:'recommend', expertWhy:'A recommendation service over product attributes, stock and each customer\u2019s history, offered to the rep as a ranked list. Pre-approved substitutes can later apply automatically.',
    autoBest:'review', autoOk:['assist','auto'], autoNote:'Medium stakes: the rep confirms the substitute, with automatic application for substitutes the customer has already accepted.',
    discoveries:[{title:'Substitution lives in heads', text:'Inventory data is accurate to the hour. Substitution knowledge is in experienced reps\u2019 heads and nowhere else.', effect:'Data readiness: start capturing which substitutes customers accept.'},{title:'A list for the top 500', text:'The product team maintains a curated substitute list for the top 500 products.', effect:'Partial data: enough to start with rules for the top sellers.'}],
    expertFeas:'mid', expertValue:'mid', realityNote:'A good use case that needs its data created first. Start with the curated list as rules and capture acceptances; recommendation follows.',
    metric:'Backordered lines per hundred orders, and substitute acceptance rate', guardrails:['logging','sampling','escalation'],
    valueHyp:'Fill a third of backordered lines with accepted substitutes.',
    dataNeeded:'Product attributes, live stock, and a record of substitutes offered and accepted per customer.'},
   {id:'A6', name:'Take orders by phone', who:'Phone reps', volume:'900 calls a day', systems:'Phone system, ERP',
    notes:'Reps take orders over the phone while keying them into the ERP, repeating product names back to confirm. Calls are already recorded for quality. Complex orders mean long calls and callbacks.',
    pain:'Seven-minute average call; typing while talking causes errors and slows the customer down.',
    expert:{shape:'extract', shapeAlt:['coordinate'], input:'media', inputAlt:[], rep:'high', repAlt:[], stakes:'mid', stakesAlt:[]},
    profileNotes:{shape:'Underneath the conversation, the rep is pulling order facts out of what the customer says: extraction, from speech.', input:'Audio: the inputs are live calls and recordings.', rep:'Nine hundred a day.', stakes:'Same as a keyed order: medium.'},
    fit:{best:['speech'], ok:['extract','agent','converse']},
    fitNotes:{speech:'Speech-to-text turns the call into text as it happens; extraction then drafts the order from the transcript. Speech is the capability that unlocks the rest.', extract:'Workable, but only after transcription. On its own it cannot hear.', agent:'Workable later: transcribe, extract, create the order, read it back.', converse:'A voice assistant taking orders is possible but a big change for customers who like their rep. Start by helping the rep.', vision:'There is nothing to look at on a phone call.'},
    poorNote:'The input here is speech. Start with the capability that turns speech into something a system can use.',
    expertPick:'speech', expertWhy:'Live transcription feeding the same order-extraction service as the emails, so the rep confirms a drafted order instead of typing it.',
    autoBest:'review', autoOk:['assist'], autoNote:'Medium stakes: the rep confirms the drafted order on the call. Full automation would mean a voice bot, a different and larger change.',
    discoveries:[{title:'Already recorded, with consent', text:'Calls are recorded for quality and the consent notice is in place.', effect:'Data and compliance: ready.'},{title:'A transcript changes nothing alone', text:'Reps key orders during the call. A transcript only helps if it feeds order capture.', effect:'Value depends on pairing with the order-capture use case.'}],
    expertFeas:'high', expertValue:'mid', realityNote:'Feasible now, valuable when paired with order capture. On its own, a medium-value companion.',
    metric:'Average call length, and phone-order error rate', guardrails:['threshold','privacy','sampling'],
    valueHyp:'Cut average call length by two minutes and bring phone-order errors in line with email.',
    dataNeeded:'Call audio with consent, the product catalogue with spoken aliases, and the order-extraction service.'},
  ]},
 B:{ id:'B', name:'Invoice to payment (AP)', fn:'Finance',
  intro:'Nine thousand supplier invoices a month arrive by email, portal and post. Eleven people capture, match, chase, approve and pay. Each invoice costs $9.40 to process; the best teams manage under $3. Walk the process to find out where the gap lives.',
  steps:[
   {id:'B1', name:'Capture invoice data', who:'AP clerks', volume:'9,000 invoices a month', systems:'Email, scanner, ERP',
    notes:'Invoices arrive as email PDFs (70%), through a supplier portal (15%) and as paper that gets scanned (15%). A clerk keys supplier, invoice number, date, PO number, line amounts and tax into the ERP. Template-based OCR handles the 30 biggest suppliers; everything else is typed.',
    pain:'$9.40 per invoice against a benchmark under $3; keying errors cause payment disputes.',
    expert:{shape:'extract', shapeAlt:[], input:'text', inputAlt:['media'], rep:'high', repAlt:[], stakes:'mid', stakesAlt:[]},
    profileNotes:{shape:'Reading a document and getting the fields out: extraction.', input:'PDFs and scans: unstructured documents (the scans lean toward images).', rep:'Nine thousand a month, from 1,200 suppliers.', stakes:'A wrong amount is usually caught at matching: medium.'},
    fit:{best:['extract'], ok:['agent','vision','rules']},
    fitNotes:{extract:'Extraction across 1,200 layouts including scans is the core of modern AP automation.', agent:'Workable: extract and post to the ERP. Prove extraction accuracy first.', vision:'Workable for the scanned paper, but document extraction already includes reading scans. You do not need a separate vision project.', rules:'Template OCR is the rules approach already in place. It covers 30 suppliers out of 1,200.', classify:'Knowing it is an invoice is not the problem. Reading it is.'},
    poorNote:'Documents need reading into fields. Pick the capability that reads documents.',
    expertPick:'extract', expertWhy:'Document extraction for all channels, posting to the ERP with field-level confidence. Clerks review low-confidence fields only.',
    autoBest:'review', autoOk:['auto'], autoNote:'Medium stakes: review low-confidence fields, auto-post the rest. Over time the threshold moves.',
    discoveries:[{title:'Twelve hundred layouts', text:'1,200 supplier formats. The scanned paper is often skewed, stamped or handwritten on.', effect:'Extraction handles variety; scans will have lower confidence and more review.'},{title:'OCR for thirty', text:'The existing template OCR covers the top 30 suppliers only and breaks when they change layout.', effect:'A clear baseline to beat.'}],
    expertFeas:'high', expertValue:'high', realityNote:'The most proven AP use case there is. Digital inputs, clear return, low integration effort. Quick win.',
    metric:'Cost per invoice, and fields corrected per hundred invoices', guardrails:['threshold','sampling','rollback'],
    valueHyp:'Cut capture cost per invoice by two thirds and remove most keying errors.',
    dataNeeded:'A few thousand past invoices with the correct ERP record; access to the mailbox, portal and scanner output.'},
   {id:'B2', name:'Match invoice to order and receipt', who:'ERP, with clerk follow-up', volume:'9,000 a month', systems:'ERP',
    notes:'Each invoice is compared to the purchase order and the goods receipt: same items, quantities and prices. The ERP does this automatically and about 70% match. The other 30% drop into an exception queue.',
    pain:'A 30% exception rate, three times what well-run teams see.',
    expert:{shape:'check', shapeAlt:[], input:'structured', inputAlt:[], rep:'high', repAlt:[], stakes:'mid', stakesAlt:['low']},
    profileNotes:{shape:'Comparing against what is expected and flagging differences: check and flag.', input:'Three structured records in the ERP.', rep:'Every invoice.', stakes:'A false match could pay the wrong amount: medium.'},
    fit:{best:['rules'], ok:['anomaly','classify','fix']},
    fitNotes:{rules:'This is deterministic comparison of structured records, and the ERP already does it. The opportunity is not to replace the matching but to fix why 30% fail.', anomaly:'Workable for the near misses: unit conversions, partial shipments and rounding that rules reject but a person would accept.', classify:'Workable for sorting exceptions by root cause so they route to the right person.', fix:'Half the exceptions come from receipts recorded late. Fixing that upstream would do more than any tool here.', extract:'The data is already structured. There is nothing to extract.', agent:'Nothing to coordinate yet; the match is instant. The chasing comes in the next step.'},
    poorNote:'Three structured records are being compared. That is a rule, and it already exists.',
    expertPick:'rules', expertWhy:'Keep the rules. Add tolerance and fuzzy matching for near misses, and fix late receiving upstream. Do not buy AI for a step your ERP already performs.',
    autoBest:'auto', autoOk:['review'], autoNote:'Deterministic matching should run fully automatically, as it does today.',
    discoveries:[{title:'Late receipts', text:'The exception rate is high mainly because the warehouse records receipts a day or two after delivery, so invoices arrive before the receipt exists.', effect:'Upstream process fix: the biggest lever is not in AP at all.'},{title:'Fuzzy near misses', text:'About 40% of exceptions are unit conversions, partial shipments or rounding differences.', effect:'A tolerance rule or fuzzy matching clears many of these.'}],
    expertFeas:'high', expertValue:'mid', realityNote:'Very feasible because it is mostly configuration and process. Medium value on its own, but it shrinks the next step.',
    metric:'Exception rate, and share of exceptions caused by late receipts', guardrails:['logging','sampling','rollback'],
    valueHyp:'Cut the exception rate from 30% toward 10% through tolerance rules and timely receiving.',
    dataNeeded:'Exception history with root causes; receiving timestamps.'},
   {id:'B3', name:'Resolve exceptions', who:'AP clerks and buyers', volume:'2,700 a month', systems:'ERP, email, receiving notes',
    notes:'For each mismatch a clerk works out what happened: no PO was raised, the receipt is missing, or the price differs. They email the buyer or the warehouse, wait, chase, sometimes ask the supplier, then decide to pay, short-pay or hold.',
    pain:'Twelve days average to resolve; buyers answer AP emails in four days; suppliers call about late payment.',
    expert:{shape:'coordinate', shapeAlt:['decide'], input:'text', inputAlt:['structured'], rep:'mid', repAlt:['high'], stakes:'mid', stakesAlt:[]},
    profileNotes:{shape:'Most of the time goes to chasing people and gathering evidence across systems: coordination, ending in a decision.', input:'Emails and free-text receiving notes, plus ERP records.', rep:'Nearly three thousand a month, but each one is a small investigation.', stakes:'Paying wrongly, or holding a good supplier: medium.'},
    fit:{best:['agent'], ok:['classify','summarize','retrieve','fix']},
    fitNotes:{agent:'An agent can gather the PO, receipt and invoice, identify the likely cause, draft the email to the buyer, chase, and propose a resolution for the clerk to approve.', classify:'Workable as a first step: categorize the root cause and route to the right person automatically.', summarize:'Workable: a one-paragraph case summary saves the clerk reassembling the story each time.', retrieve:'Workable for finding the relevant PO, contract price or receiving note.', fix:'Fewer exceptions upstream means less to resolve. Pair this with the receiving fix.', rules:'The evidence and the replies are unstructured. Rules alone cannot chase a buyer.'},
    poorNote:'This step is a small investigation with people to chase. Pick the capability that can do the legwork.',
    expertPick:'agent', expertWhy:'An agent that assembles the case, drafts and sends the chase, and proposes the resolution. A clerk approves each resolution to begin with.',
    autoBest:'review', autoOk:['assist'], autoNote:'Medium stakes and actions across systems: the agent proposes, a clerk approves. Prove it before letting it short-pay anyone on its own.',
    discoveries:[{title:'The four-day wait', text:'Buyers take four days on average to answer AP. The waiting, not the deciding, is most of the twelve-day cycle.', effect:'Value: automated chasing with escalation attacks the real bottleneck.'},{title:'Three root causes', text:'Root causes split roughly 45% missing PO, 30% late receipt, 25% price mismatch.', effect:'Each cause has a standard playbook the agent can follow.'}],
    expertFeas:'mid', expertValue:'high', realityNote:'High value, medium feasibility: the agent touches several systems and needs stopping rules. A strategic bet that gets easier after the quick wins.',
    metric:'Days to resolve an exception, and supplier late-payment calls per month', guardrails:['logging','escalation','threshold'],
    valueHyp:'Cut resolution from twelve days to four and end most late-payment calls.',
    dataNeeded:'Exception cases with their resolution; access to email and the ERP; the playbook per root cause.'},
   {id:'B4', name:'Approve for payment', who:'Budget approvers', volume:'9,000 a month', systems:'ERP approval workflow',
    notes:'Matched invoices go to an approver based on value. Most approvals take under ten seconds. Last year the team recovered $310,000 in duplicate payments after the fact; the amount not recovered is unknown. Bank-detail changes arrive by email from suppliers.',
    pain:'Approval is theatre for the routine invoices and too thin for the risky ones.',
    expert:{shape:'check', shapeAlt:['decide'], input:'structured', inputAlt:[], rep:'high', repAlt:[], stakes:'high', stakesAlt:['mid']},
    profileNotes:{shape:'The useful work here is spotting the invoices that should not be paid: check and flag. The approval click is a decision, but not the one that adds value.', input:'Structured payment records, supplier master data and history.', rep:'Every invoice.', stakes:'Duplicate and fraudulent payments: high.'},
    fit:{best:['anomaly','rules'], ok:['recommend','predict']},
    fitNotes:{anomaly:'Duplicates, unusual amounts, new bank details and first-time suppliers are anomalies against history. Score the risk so approvers spend their attention there.', rules:'Under-threshold, cleanly matched, known-supplier invoices can be auto-approved by rule, freeing attention for the rest.', recommend:'Workable: present approvers a risk-ranked queue with reasons.', predict:'Workable: a fraud-likelihood score is a prediction. Anomaly detection is the more natural framing when you have little labelled fraud.', draft:'Nothing to write here.', agent:'Letting a tool approve payments on its own is the wrong place to start.'},
    poorNote:'The value here is catching the payments that should not happen. Pick the capability that spots what does not fit.',
    expertPick:'anomaly', expertWhy:'Rules auto-approve the routine; anomaly detection flags the unusual with a reason; approvers review only the flagged. Bank-detail changes always go to a person.',
    autoBest:'review', autoOk:['assist'], autoNote:'High stakes on the flagged items, low on the routine: automate the routine by rule, review everything flagged. Never fully automate payment approval.',
    discoveries:[{title:'The duplicates you found', text:'$310,000 in duplicate payments was recovered last year. Nobody knows how much was not found.', effect:'Value: even a modest catch rate pays for the project.'},{title:'Ten-second approvals', text:'Approvers approve 92% of invoices in under ten seconds.', effect:'Change: approvers will welcome a shorter, riskier queue.'}],
    expertFeas:'high', expertValue:'high', realityNote:'Structured data, clear signals, a receptive audience and a hard-dollar prize. Quick win.',
    metric:'Duplicate and erroneous payments caught before paying, and approver minutes per month', guardrails:['logging','escalation','sampling'],
    valueHyp:'Catch most duplicate and suspicious payments before they leave, and cut approver time by 80%.',
    dataNeeded:'Payment history, supplier master data with change logs, and the recovered-duplicate cases as examples.'},
   {id:'B5', name:'Answer supplier payment questions', who:'AP clerks', volume:'1,400 emails a month', systems:'ERP, supplier portal',
    notes:'Suppliers email to ask when they will be paid or why an invoice was short-paid. A clerk finds the invoice in the ERP, checks its status, and replies. A supplier portal exists that shows the same information; 15% of suppliers use it.',
    pain:'Six minutes per question; about 140 hours a month answering questions the portal could answer.',
    expert:{shape:'lookup', shapeAlt:[], input:'structured', inputAlt:['text'], rep:'high', repAlt:[], stakes:'low', stakesAlt:[]},
    profileNotes:{shape:'Find the status and pass it on: look up and answer.', input:'The answer lives in structured ERP records.', rep:'Fourteen hundred a month, nearly identical.', stakes:'Low.'},
    fit:{best:['fix','retrieve','converse'], ok:['rules','draft','agent']},
    fitNotes:{fix:'The portal already answers this. Driving adoption (make the portal the default in supplier onboarding, put the link in every remittance) removes the question.', retrieve:'Retrieval over the ERP with a drafted reply answers what the portal does not catch.', converse:'A conversational assistant on the portal lets suppliers ask in their own words.', rules:'Workable: automatic payment-status notifications remove many questions before they are asked.', draft:'Workable with the facts retrieved first.', agent:'Workable but oversized for a lookup.'},
    poorNote:'The answer already exists in a system. Pick the capability, or the fix, that gets it to the supplier.',
    expertPick:'fix', expertWhy:'Adoption first: make the portal the default channel and send status notifications. Then retrieval-based replies for the remainder.',
    autoBest:'auto', autoOk:['review'], autoNote:'Low stakes, structured answers: self-service and automatic replies fit.',
    discoveries:[{title:'The unused portal', text:'The supplier portal shows payment status already. 15% of suppliers have logged in this year.', effect:'Fix before build.'},{title:'Six minutes each', text:'Each question takes a clerk about six minutes across the ERP and email.', effect:'About 140 hours a month: real, but small next to the other steps.'}],
    expertFeas:'high', expertValue:'low', realityNote:'Easy and cheap, but the prize is under one person. A fill-in: do it when convenient, mostly by fixing adoption.',
    metric:'Supplier status questions per month, and portal logins', guardrails:['escalation','sampling','rollback'],
    valueHyp:'Cut supplier status questions by 70% through portal adoption and notifications.',
    dataNeeded:'ERP payment status, the portal, and supplier contact data.'},
  ]},
 C:{ id:'C', name:'Replenishment planning', fn:'Procurement & inventory',
  intro:'Six buyers decide every week what to order for 18,000 products across three warehouses. Six percent of order lines stock out while $14M of inventory sits in excess. Walk the weekly cycle.',
  steps:[
   {id:'C1', name:'Forecast demand by product and warehouse', who:'Buyers', volume:'18,000 products, weekly', systems:'ERP history, spreadsheets',
    notes:'Each week a buyer pulls twelve months of sales for their categories into a spreadsheet, eyeballs the trend, adjusts for seasonality and known promotions, and writes down an expected weekly demand per product per warehouse.',
    pain:'Sixty percent of the week in spreadsheets; forecasts systematically high on slow movers and low on fast ones.',
    expert:{shape:'predict', shapeAlt:[], input:'structured', inputAlt:[], rep:'high', repAlt:[], stakes:'mid', stakesAlt:[]},
    profileNotes:{shape:'Putting a number on next week\u2019s demand: estimate and forecast.', input:'Sales history in the ERP: structured.', rep:'Eighteen thousand products every week.', stakes:'A bad forecast means a stockout or excess: medium, and it compounds.'},
    fit:{best:['predict'], ok:['anomaly','rules']},
    fitNotes:{predict:'Statistical and machine-learning forecasting at product and warehouse level is a mature capability and beats eyeballing at scale.', anomaly:'Workable as a companion: flag products whose demand pattern has changed so a planner looks.', rules:'A moving average is a rule, and roughly what the spreadsheets do today. It is the baseline, not the solution.', draft:'Nothing to write.', converse:'Nobody needs to chat with the forecast.'},
    poorNote:'A number about the future is needed for eighteen thousand products. Pick the capability that estimates.',
    expertPick:'predict', expertWhy:'Forecasting for all products with an exception view: planners review the products where the model is unsure or the pattern changed, and override with a reason.',
    autoBest:'review', autoOk:['auto'], autoNote:'Medium stakes at scale: automate the stable products, review the exceptions, and log overrides so the model learns which ones were right.',
    discoveries:[{title:'Seven years of history', text:'The ERP holds seven years of weekly sales by product and warehouse. Promotion history lives in marketing\u2019s spreadsheets.', effect:'Data: mostly ready; promotions need joining.'},{title:'No black boxes', text:'Buyers say they will not trust a number they cannot see the reasoning for.', effect:'Change: forecasts must show their drivers and allow overrides.'}],
    expertFeas:'mid', expertValue:'high', realityNote:'High value and the data exists. Feasibility is medium because trust and adoption decide whether the numbers get used. A strategic bet worth starting now.',
    metric:'Forecast error by product class, and buyer hours in spreadsheets', guardrails:['sampling','logging','rollback'],
    valueHyp:'Cut forecast error by a third and give buyers back half their week.',
    dataNeeded:'Sales history by product, warehouse and week; promotion calendar; stockout records (demand you could not see).'},
   {id:'C2', name:'Gather supplier and market signals', who:'Buyers', volume:'300 emails a week', systems:'Individual inboxes',
    notes:'Suppliers email about lead-time changes, price increases, discontinued items and shortages. The emails go to whichever buyer the supplier knows. Important ones get acted on if the buyer is not on holiday; the rest are found later, when the stockout has already happened.',
    pain:'Late discovery of lead-time changes causes roughly 30% of stockouts.',
    expert:{shape:'extract', shapeAlt:['summarize','route'], input:'text', inputAlt:[], rep:'high', repAlt:['mid'], stakes:'mid', stakesAlt:[]},
    profileNotes:{shape:'Pull the facts out of supplier emails (which product, what changed, from when) so the plan can use them: extraction, with some sorting.', input:'Emails: unstructured text.', rep:'Three hundred a week.', stakes:'A missed lead-time change becomes a stockout: medium.'},
    fit:{best:['extract','summarize'], ok:['classify','agent']},
    fitNotes:{extract:'Turning "lead time on X moves to 6 weeks from May" into a structured update is extraction. The plan can then use it.', summarize:'A weekly digest of supplier changes by category is a fair first step and helps buyers see the picture.', classify:'Workable: route each email to the right buyer and flag urgency.', agent:'Workable later: extract the change and update the lead time in the ERP for a buyer to confirm.', predict:'You are not forecasting. The supplier is telling you.'},
    poorNote:'The information is sitting in emails. Pick the capability that gets it out.',
    expertPick:'extract', expertWhy:'A shared supplier mailbox, extraction of changes into structured updates, and a buyer confirming each update before it changes the plan.',
    autoBest:'review', autoOk:['assist'], autoNote:'Medium stakes: a buyer confirms each extracted change before it alters purchasing.',
    discoveries:[{title:'No shared mailbox', text:'Supplier emails go to individual buyers. There is no shared address and no record when someone leaves.', effect:'Step zero: create the shared channel so the inputs are captured.'},{title:'Thirty percent of stockouts', text:'Late discovery of lead-time changes explains roughly 30% of stockouts.', effect:'Value: directly attacks the stockout figure.'}],
    expertFeas:'mid', expertValue:'high', realityNote:'High value, and the tooling is proven. The missing piece is a shared mailbox, which is a process change, not a technology one. Strategic bet with a fast start.',
    metric:'Days from supplier notice to plan update, and stockouts attributed to late signals', guardrails:['threshold','logging','escalation'],
    valueHyp:'Cut stockouts caused by late supplier signals by half.',
    dataNeeded:'A shared supplier mailbox; past supplier emails with the change they announced; the supplier and product master.'},
   {id:'C3', name:'Set order quantities and timing', who:'Buyers', volume:'2,100 purchase decisions a week', systems:'Spreadsheets, ERP',
    notes:'Given the forecast and stock on hand, a buyer decides how much of each product to order for each warehouse and when, balancing supplier minimums, truck fill, budget, shelf life and lead times. Most of these constraints are in the buyer\u2019s head; a few are in notes.',
    pain:'Half-empty trucks and stockouts on the same day; $14M excess inventory.',
    expert:{shape:'allocate', shapeAlt:['decide'], input:'structured', inputAlt:['tacit'], rep:'high', repAlt:[], stakes:'mid', stakesAlt:['high']},
    profileNotes:{shape:'Many products, limited money and truck space, many constraints: allocate and schedule.', input:'Stock, forecasts and costs are structured. Many constraints are unwritten.', rep:'Two thousand decisions every week.', stakes:'Cash tied up and service levels: medium to high.'},
    fit:{best:['optimize'], ok:['predict','recommend','rules']},
    fitNotes:{optimize:'Choosing quantities and timing under constraints to minimise cost and stockouts is optimization, a mature technique that long predates generative AI.', predict:'Workable as the input: an optimizer is only as good as the forecast it consumes.', recommend:'Workable as a lighter start: rank suggested orders for the buyer rather than solve the whole plan.', rules:'Reorder-point rules are the status quo in disguise. They ignore truck fill and budget.', draft:'Nothing to write.', converse:'Nobody needs to chat with the plan.'},
    poorNote:'This is a balancing problem with constraints. Pick the capability that finds the best plan.',
    expertPick:'optimize', expertWhy:'An optimizer that proposes the weekly buy plan with its constraints visible, which buyers adjust. Their adjustments become new constraints over time.',
    autoBest:'review', autoOk:['assist'], autoNote:'Medium to high stakes with unwritten constraints: buyers review the proposed plan every week. Full automation would repeat the last failure.',
    discoveries:[{title:'Constraints in heads', text:'Supplier minimums, truck fill and budget rules are known but live in buyers\u2019 heads and scattered notes.', effect:'Data readiness: constraints must be captured explicitly first.'},{title:'The last attempt failed', text:'A previous optimization project was abandoned because buyers could not override its output.', effect:'Change: overrides with reasons are non-negotiable.'}],
    expertFeas:'low', expertValue:'high', realityNote:'The biggest prize in the process and the hardest to land: constraints to capture, trust to rebuild. A strategic bet that follows forecasting, not one that leads.',
    metric:'Stockout rate, excess inventory value, and average truck fill', guardrails:['logging','rollback','sampling'],
    valueHyp:'Cut excess inventory by $4M and stockouts by a third at the same truck fill.',
    dataNeeded:'Forecasts, stock, lead times, written constraints (minimums, truck capacity, budget, shelf life), and past plans with their outcomes.'},
   {id:'C4', name:'Create and send purchase orders', who:'Buyers', volume:'2,100 POs a week', systems:'ERP, email',
    notes:'Once quantities are decided, the buyer creates each PO in the ERP, exports it, emails it to the supplier, and later files the supplier\u2019s acknowledgment, which arrives as an email in one of sixty formats.',
    pain:'A morning a week per buyer on clerical work.',
    expert:{shape:'coordinate', shapeAlt:[], input:'structured', inputAlt:['text'], rep:'high', repAlt:[], stakes:'low', stakesAlt:[]},
    profileNotes:{shape:'Moving information between systems and people: coordinate and update.', input:'The PO data is structured in the ERP. Acknowledgments come back as text.', rep:'Two thousand a week.', stakes:'Low; errors are visible and reversible.'},
    fit:{best:['rules'], ok:['agent','extract']},
    fitNotes:{rules:'Creating and sending a PO from decided quantities is deterministic. The ERP can do it automatically; no AI is needed for this step.', agent:'Workable for the acknowledgments, which are unstructured. Oversized for the sending.', extract:'Workable for reading acknowledgments into confirmed dates and quantities.', predict:'Nothing to forecast.', converse:'Nothing to converse about.'},
    poorNote:'This step is clerical and deterministic. Ask what a rule would do before asking what AI would do.',
    expertPick:'rules', expertWhy:'Switch on the ERP\u2019s PO generation and sending. Use extraction only for the acknowledgments coming back.',
    autoBest:'auto', autoOk:['review'], autoNote:'Low stakes, deterministic: fully automatic.',
    discoveries:[{title:'The feature nobody switched on', text:'The ERP has automatic PO generation and emailing. It was never configured.', effect:'Feasibility: configuration, not a project.'},{title:'Sixty acknowledgment formats', text:'Supplier acknowledgments arrive as emails in about sixty formats.', effect:'The one place extraction earns its keep here.'}],
    expertFeas:'high', expertValue:'mid', realityNote:'A quick win that is barely an AI project: configure the ERP, then add extraction for acknowledgments.',
    metric:'Buyer hours on PO administration, and unacknowledged POs after 48 hours', guardrails:['logging','rollback','sampling'],
    valueHyp:'Return a morning a week to each buyer.',
    dataNeeded:'ERP configuration; sample acknowledgment emails.'},
   {id:'C5', name:'Decide what to do with excess stock', who:'Buyers and finance', volume:'1,900 flagged products a month', systems:'ERP aging report, contracts',
    notes:'Monthly, a report lists slow-moving and excess products. For each, someone decides: promote it, return it to the supplier if the contract allows, transfer it between warehouses, or write it off. The decision needs sales trend, return terms and margin, and finance signs off write-offs.',
    pain:'The list is long, the decision is slow, and $14M sits on the shelves.',
    expert:{shape:'decide', shapeAlt:['suggest'], input:'structured', inputAlt:['text'], rep:'mid', repAlt:[], stakes:'mid', stakesAlt:[]},
    profileNotes:{shape:'A judgment call per product with money attached: judge and decide, helped by ranked options.', input:'Aging and margin data are structured. Return terms are in contracts.', rep:'Monthly, nineteen hundred at a time.', stakes:'Write-offs and supplier relationships: medium.'},
    fit:{best:['recommend'], ok:['anomaly','predict','summarize','retrieve']},
    fitNotes:{recommend:'Ranking the four actions per product with the evidence (trend, terms, margin, transfer demand) lets buyers decide quickly and consistently.', anomaly:'Workable upstream: flag products becoming excess earlier, before the report.', predict:'Workable as an input: will this product sell down on its own?', summarize:'Workable: a one-line brief per product.', retrieve:'Workable for finding the return terms in 900 contracts.', agent:'Automating write-offs is not where to start. Finance signs those off for a reason.'},
    poorNote:'Someone accountable decides what happens to money on a shelf. Pick the capability that prepares that decision.',
    expertPick:'recommend', expertWhy:'Decision support: a ranked action per product with reasons, return terms retrieved from contracts, and buyers deciding in a fraction of the time.',
    autoBest:'assist', autoOk:['review'], autoNote:'Medium stakes and finance sign-off: a person decides each one, faster.',
    discoveries:[{title:'Sign-off required', text:'Aging data is clean. Write-offs need finance sign-off by policy.', effect:'Assist mode fits the governance already in place.'},{title:'Terms in 900 contracts', text:'Return-to-supplier terms are in 900 contract PDFs.', effect:'Retrieval over contracts is part of the work.'}],
    expertFeas:'mid', expertValue:'mid', realityNote:'Solid and sensible, medium on both axes. Build toward it once forecasting is in place.',
    metric:'Excess inventory value, and days from flag to action', guardrails:['logging','escalation','sampling'],
    valueHyp:'Act on excess within two weeks of flagging and cut it by a quarter.',
    dataNeeded:'Aging and margin by product, contract return terms, transfer demand by warehouse.'},
  ]},
};

/* ---------- Trail events: the traps ---------- */
const EVENTS = {
  E1:{title:'The demo', text:'Leadership saw a vendor demo last week and now wants "a chatbot" live by the end of next quarter. Your sponsor asks you to make it happen.',
    opts:[{t:'Start scoping the chatbot. It is what leadership asked for.', s:0, fb:'A chatbot is a capability, not a use case. Without a process and a step, you will build a front door to nothing in particular.'},
          {t:'Ask which process it would improve and which step, then evaluate a conversational assistant alongside the other capability types for that step.', s:2, fb:'Tools are answers. You do not have a question yet. Anchor the request to a step in a process and the right capability may or may not be a chatbot.'},
          {t:'Push back: chatbots do not work.', s:0, fb:'Some do, in the right place. Dismissing the tool is the same mistake as worshipping it: it skips the work.'}]},
  E2:{title:'The brand name', text:'A colleague insists your team needs one specific, well-known product. "Everyone uses it. Just buy it and move on."',
    opts:[{t:'Buy it. A known brand is the safe choice.', s:0, fb:'Brands change, get acquired and get outrun. Buying before you know what the step needs makes the tool the requirement.'},
          {t:'Write down the capability the step needs (what it must read, decide or produce, at what accuracy and volume), then evaluate any option, including that one, against it.', s:2, fb:'The capability requirement outlives any vendor. It also makes the comparison honest, and it is the thing you can hand to procurement.'},
          {t:'Ban vendors and build everything in-house.', s:0, fb:'Building is a valid option for some capabilities, but deciding it before you know the requirement is the same error in a different jacket.'}]},
  E3:{title:'The workaround', text:'Digging into a step, you find it exists because two systems do not share a field. Somebody re-keys the same information every day, and has for six years.',
    opts:[{t:'Automate the re-keying with an agent. Fast relief.', s:1, fb:'It works, and sometimes it is the pragmatic bridge. But you have now bought a tool to preserve a defect. Note the real fix and a date to make it.'},
          {t:'Fix the integration or the form so the field flows through, then see what work is left.', s:2, fb:'Remove the cause and the step may vanish. Automating a broken process only makes it break faster.'},
          {t:'Add a second person to check the re-keying.', s:0, fb:'Now two people preserve the defect.'}]},
  E4:{title:'The spreadsheet archipelago', text:'The "data" a use case depends on turns out to live in fourteen personal spreadsheets with different column names, two of which belong to someone who left in March.',
    opts:[{t:'Feed the spreadsheets to a model and see what comes out.', s:0, fb:'What comes out will look plausible and be wrong in ways nobody can check. Uncaptured or inconsistent data is a step-zero problem, not something a model fixes.'},
          {t:'Treat data capture as step zero: agree where the data lands and in what shape, then pilot on the subset that is already clean.', s:2, fb:'Most use cases that fail, fail here. Capturing the data properly is unglamorous and it is the work.'},
          {t:'Drop the use case.', s:1, fb:'Sometimes right, but check the size of the prize first. If the value is large, a data-capture project is the first phase, not a reason to stop.'}]},
  E5:{title:'The team meeting', text:'You present the idea to the team whose work it touches. The room goes quiet. Someone asks whether this means layoffs.',
    opts:[{t:'Reassure them that nothing will change.', s:0, fb:'Something will change, or why do it? People can tell. Vague reassurance costs you the trust you need for the pilot.'},
          {t:'Be specific: which tasks change, what they will do with the time, how they will be involved in testing, and how errors will be caught.', s:2, fb:'Specifics are respect. The people who do the work today are also the only ones who can tell you when the tool is wrong.'},
          {t:'Present it to their manager only, next time.', s:0, fb:'The tool will be judged by the people who use it. Cutting them out delays the conversation and worsens it.'}]},
  E6:{title:'The metric', text:'Your sponsor asks the question that decides whether this becomes a program or a slide: "How will we know it worked?"',
    opts:[{t:'Count the AI features we ship this year.', s:0, fb:'Activity, not outcome. Shipping features is easy. Changing the step is the point.'},
          {t:'Measure the step now (time, error rate, cost per item, cycle time) and compare the pilot against that baseline.', s:2, fb:'A baseline measured before the pilot is the difference between a result and an anecdote.'},
          {t:'Run a satisfaction survey after launch.', s:1, fb:'Useful alongside a baseline, not instead of one. Satisfaction can rise while the work gets worse.'}]},
};
const EVENT_TRIGGERS = {afterTerrain:'E1', afterStep2:'E2', afterStep4:'E3', beforeReality:'E4', beforeCanvas:'E5', beforeDebrief:'E6'};

/* ---------- Debrief content ---------- */
const TAKEAWAYS = [
  {h:'Start from the work, not the tool', d:'A capability is an answer. Find the question first: a process, a step, a measurable pain.'},
  {h:'A hotspot has four ingredients', d:'Volume, repetition, a pain you can measure, and inputs that are already captured. Pain alone is not enough.'},
  {h:'The shape of the work points to the capability', d:'Reading, sorting, looking up, writing, condensing, estimating, checking, ranking, allocating, deciding, chasing. Each has a capability type behind it. Brands come last.'},
  {h:'Ask what a rule would do first', d:'If the logic can be written down, a rule or your existing system is cheaper and more predictable. If the step exists because of a broken handoff, fix the handoff.'},
  {h:'Match autonomy to stakes', d:'Assist when a person must own the call. Review when the routine is safe and exceptions are not. Automate when errors are cheap and reversible.'},
  {h:'Reality check before you pitch', d:'Data readiness, risk, change effort and integration on one axis; value on the other. Quick wins build the trust that strategic bets need.'},
  {h:'Measure the baseline before the pilot', d:'Time, error rate, cost per item, cycle time. Without a baseline you will have an anecdote, not a result.'},
];
const RANKS = [
  {min:0,   name:'Day tripper',      d:'You saw the terrain. Next time, spend longer at each step before reaching for the toolkit.'},
  {min:40,  name:'Trail scout',      d:'You can find the hotspots and name most of the work. Practise the matching and the reality check.'},
  {min:60,  name:'Cartographer',     d:'You dissect processes well and match capabilities sensibly. The reality check is where the last points live.'},
  {min:80,  name:'Expedition lead',  d:'You start from the work, match the capability, size the autonomy and check reality. Take a team through it.'},
];

const DISCUSS = {
  terrain:'Which signal is evidence of a hotspot, and which is just loud? Agree the three before you lock them in.',
  profile:'Where do you disagree about the shape of this work? The disagreement usually reveals two steps hiding in one.',
  match:'Would a rule do this? What makes it need AI? Who is accountable if it is wrong?',
  reality:'What would you need to see to move this one to the right on the map? Who owns that?',
  canvas:'Who will measure the baseline, and by when?',
};
